### ISSUE TITLE
Failing Read The Docs Build

### ISSUE THREAD

**Issue by nbmurphy** [sdss/sdss_install#1]
This seems to be unrelated to the `.travis.yml` `install:` line `- python setup.py install `.

**Comment by nbmurphy** [comment]
Hey @albireox and @havok2063,
Do you have any insights about why the Read The Docs build is failing?
https://readthedocs.org/projects/sdss-install/builds/7860810/
I was able to fix some failed Travis CI builds, but I don't have much intuition for Read The Docs and Sphinx.

**Comment by albireox** [comment]
Hi @nbmurphy,

I think the problem is that in `bin` you renamed `sdss_install` to `sdssinstall` but you didn't change the name in `setup.py`. If you go there and remove the `_` in line 41 I think it will work.

**Comment by nbmurphy** [comment]
> Hi @nbmurphy,
> 
> I think the problem is that in `bin` you renamed `sdss_install` to `sdssinstall` but you didn't change the name in `setup.py`. If you go there and remove the `_` in line 41 I think it will work.

That did it, Thanks!

**Comment by nbmurphy** [comment]
> Hi @nbmurphy,
> 
> I think the problem is that in `bin` you renamed `sdss_install` to `sdssinstall` but you didn't change the name in `setup.py`. If you go there and remove the `_` in line 41 I think it will work.

That did it, thanks @albireox! Also, thanks @havok2063 for your Slack discussion that touched on this among other topics.
