### ISSUE TITLE
unknown environment variables in sdss_install

### ISSUE THREAD

**Issue by havok2063** [sdss/sdss_install#10]
When attempting to run `sdss_install -G tree master` I get the following messages
```
sdssinstall - ERROR - Unable to authorize the GrqphQL client using the key 'SDSS_GITHUB_KEY'.
sdssinstall - ERROR - Unable to set the directory from the environmental variable KeyError('SDSS_INSTALL_GRAPHQL_DIR').
sdssinstall - ERROR - Unable to set the GraphQL query file.
```

Are these environment variables necessary to use `sdss_install`?  If so, where is the documentation describing how to set this up?  Docs [here](https://sdss-install.readthedocs.io/en/latest/) are blank.

**Comment by nbmurphy** [comment]
Before using sdss_install, the export statement in step 6 [here](https://wiki.sdss.org/display/knowledge/Wordpress+Documentation+for+sdss_install) needs to be run or added to your sdss_install module file. The GitHub key in this step can't be committed to GitHub and therefore must be added manually or by running sdss_install_bootstrap. Without this key, GraphQL functionality is absent from sdss_install.

The environmental variable `SDSS_INSTALL_GRAPHQL_DIR` is set in the sdss_install module file generated by running sdss_install_bootstrap:
`setenv [string toupper $product]_GRAPHQL_DIR $PRODUCT_DIR/graphql`
