### ISSUE TITLE
modules directory used by sdss_install should be explicitly set and placed in MODULEPATH

### ISSUE THREAD

**Issue by havok2063** [sdss/sdss_install#14]
The modulesfiles directory set manually in step 4 [here](https://wiki.sdss.org/display/knowledge/Wordpress+Documentation+for+sdss_install), which is set as `self.options.moduledir`, should be set explicitly by `sdss_install`, and placed inside the `$MODULEPATH`.  This is desired when installing `tree` so that the `setup_tree` command will know to copy the newly created module files into that directory.

**Comment by joelbrownstein** [comment]
I think I understand the approach that would keep sdss_install's products available without depending on the bootstrap.

A test could be performed, in which the value of the required `moduledir` is actually `in $MODULEPATH`.

If its isn't then prepend it (or equivalently via `module use $moduledir`
otherwise do nothing.

**Comment by nbmurphy** [comment]
Added modules.py method prepend_modulepath() which does what @joelbrownstein and @havok2063 suggested.

**Comment by havok2063** [comment]
Has this been properly tested?  It does not work for me.  Or it's not doing what I need.  It needs to be added into the environment variable that is read by the shell, `$MODULEPATH`.  This prepend only adds it locally into the Python environment used by `sdss_install`.  There may not be a real solution here other than users need to remember to always say `module use` or add it into their `bashrc`.

**Comment by havok2063** [comment]
The first two things a user needs to do to get set up is install `sdss_install` and then `tree`.  These are the steps that make sense to me. 
1. fresh install of `sdss_install`
2. if the moduledir is not in the MODULEPATH add it
3. use `sdss_install` to install the `tree`
4. sdss_install creates the tree modulefile subdirectory in the specified moduledir
5. sdss_install runs the tree Makefile which will run `setup_tree.py` which copies the created modules into all module paths specified in $MODULEPATH that have an existing `tree` subdir.  

All that being said, I think issues #16, #15, #14, #13, #11 are all related.

**Comment by joelbrownstein** [comment]
that's correct.  prepending to the MODULEPATH was a bad suggestion since it doesn't make that permanent.

**Comment by joelbrownstein** [comment]
Ben removed it.  Let's discuss a permanent solution over zoom or something, please.

**Comment by havok2063** [comment]
I think the simplest thing, for now, is to just make sure users manually run the `module use [PATH]` command to ensure the e.g. `sdss_install/github/modulefiles` is added **before** they install `tree` or any other product.  It would be nice to be able to get this to work but it's a not a high priority.  I think it's ok to close this for now.

But we should document somewhere if they install `tree` with `sdss_install` and do not find the module files in the tree module subdirectory, then it's most likely due to the modulefiles directory not in their `$MODULEPATH`

**Comment by joelbrownstein** [comment]
What if we took a lesson from sdss4tools and sdss4install?  i.e. we could put the module use in the sdss_install module file, and then force people to `module load sdss_install` to guarantee that sdss_install things are in the module path?
