### ISSUE TITLE
which versions of modules does sdss_install support?

### ISSUE THREAD

**Issue by havok2063** [sdss/sdss_install#17]
Which versions of modules, tcl, lua, etc does or will `sdss_install` support?  The releases for tcl modules are indicated here: https://modules.readthedocs.io/en/stable/NEWS.html#.  I'm using `Modules Release Tcl 1.147`.  If there is a minimum version of modules that sdss_install needs, this should be checked and caught with an error raised for versions less than that on initialization of `sdss_install`

**Comment by joelbrownstein** [comment]
Ben is applying the following version check:
python2 >= Modules Release Tcl 1.147 
python3 >= Modules Release Tcl 1.602 
we'll have to check LUA separately.

**Comment by joelbrownstein** [comment]
although `module --version` works in bash (via stdout)
and module('--version') works in python (via exec of a bash function),

we cannot extract the version information into a python string.  So this issue will remain open until we resolve this underlying issue (see https://github.com/sdss/sdss_install/issues/18).

**Comment by havok2063** [comment]
This makes sense to me.  I upgraded to `Modules 4.2.4` and things seem to be working so far.    

I commented on the `module --version` issue in #18.

**Comment by havok2063** [comment]
This info should also be included in the documentation for installation.  Related to #7.

**Comment by joelbrownstein** [comment]
Ben would you look at updating the documentation for sdss_install to include all of these details Brian has identified?

**Comment by joelbrownstein** [comment]
The issue of the python shell and the inherent sensitivity to which python version and / or which modules version has been solved as of tag 1.0.3

**Comment by joelbrownstein** [comment]
with simpler instructions at https://www.sdss.org/dr15/software/products/
