### ISSUE TITLE
Python cannot extract version from module function

### ISSUE THREAD

**Issue by nbmurphy** [sdss/sdss_install#18]

**Comment by nbmurphy** [comment]
I've tried several potential solutions:
https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/
https://www.blog.pythonlibrary.org/2016/06/16/python-101-redirecting-stdout/

**Comment by nbmurphy** [comment]
This runs in ipython2 but captures `None`

import sys
import io
import StringIO
from contextlib import contextmanager
execfile('/software/modules/init/python',globals())
@contextmanager
def stdout_redirector(stream):
    old_stdout = sys.stdout
    sys.stdout = stream
    try:
        yield
    finally:
        sys.stdout = old_stdout	
f = StringIO.StringIO()
with stdout_redirector(f):
    print(module('--version'))
print('Got stdout: "{0}"'.format(f.getvalue()))

**Comment by havok2063** [comment]
This seems to work, although I don't know why the output is captured in the err variable. 

```
p=subprocess.Popen('module --version', executable='/bin/bash', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
out,err = p.communicate()
out
b''

err
b'Modules Release 4.2.4 (2019-04-26)\n'
```

**Comment by havok2063** [comment]
@nbmurphy bumping this

**Comment by joelbrownstein** [comment]
there are only 2 pipes, stdout and stderr, so you can write your code to check stderr if stdout=''

**Comment by nbmurphy** [comment]
I’ve tried the above subprocess commands with and without the `executable='/bin/bash'`, since [the documentation](https://docs.python.org/2/library/subprocess.html#popen-constructor) says it’s very seldom needed, but both ways returns the error
```
In [5]: err
Out[5]: '/bin/sh: module: command not found\n'
```
when I replace  `executable='/bin/bash'` with `executable='/software/modules/init/python'` it returns the error
```
In [15]: err
Out[15]: '/bin/bash: module: command not found\n'
```

**Comment by joelbrownstein** [comment]
Hi @nbmurphy, I don't understand why you would ever replace /bin/bash with /software/modules/init/python -- there is no use case that I can think of where that would something to do.

**Comment by joelbrownstein** [comment]
Hi @nbmurphy, back on track for this ticket, I have a simple solution that would allow python to pull the version info out of the module function by redirecing stderr to stdout.

i.e. the following example does **not** work because it doesn't redirect stderr, and the result is printed to the terminal but $result as an empty string (which you saw in python):

$ result=`module --version`
Modules Release Tcl 1.147
$ echo "the result is $result!" 
the result is !

Conversely, this version works:

$ result=`module --version 2>&1 >/dev/null`
$ echo $result
Modules Release Tcl 1.147

which would also work in python via the subprocess.check_output()

Let me test this approach in python....

**Comment by joelbrownstein** [comment]
sorry, this is working in bash, but I still cannot get it to produce a result in python...

**Comment by havok2063** [comment]
This command works on `lore.sdss.utah.edu` as the manga user.

```
p=subprocess.Popen('module --version', executable='/bin/bash', stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
out, err = p.communicate()
out
b''
err
b'\nModules based on Lua: Version 7.7.29  2018-04-10 11:26 -05:00\n    by Robert McLay mclay@tacc.utexas.edu\n\n'

```

**Comment by havok2063** [comment]
@nbmurphy @joelbrownstein The above also works on the `manga` machine as well.  I haven't looked at your PR yet so maybe that will override this.

**Comment by joelbrownstein** [comment]
Hi @havok2063 the call to bash "module --version" is fragile depending on the system, for e.g. I get
out, err = p.communicate()
err
Out[4]: b'/bin/bash: module: command not found\n'

So we made a class to bypass bash competely, which seems to work for all TCLSH modules, and we need to extend it to LUA before completing the PR

**Comment by havok2063** [comment]
ok cool.
