### ISSUE TITLE
SDSS_GITHUB_KEY in modulefile

### ISSUE THREAD

**Issue by albireox** [sdss/sdss_install#3]
It seems the module file for `sdss_install` sets `SDSS_INSTALL_KEY` when it should be setting `SDSS_GITHUB_KEY` (last line in the the [modulefile](https://github.com/sdss/sdss_install/blob/master/etc/sdss_install.module)).

**Comment by nbmurphy** [comment]
I confirmed that there isn’t a problem with the source code in GitHub --- there’s no problem with the sdss_install etc/ module file. We are planning on opening a JIRA ticket to deprecate the environmental variable name which contains GITHUB.

**Comment by joelbrownstein** [comment]
Please use the data release component for the JIRA ticket, when ready
