### ISSUE TITLE
Allow installing external dependencies as modules

### ISSUE THREAD

**Issue by albireox** [sdss/sdss_install#39]
Based on the conversation around [idlutils](https://github.com/sdss/idlutils) we need a new feature to be able to install external (non SDSS, non sdss_install-enabled) dependencies. For the particular case of idlutils we need that when we sdss_install it, the Coyote and Goddard IDL libraries be downloaded and installed as modules.

I think the right place for defining this would be the config.ini in idlutils. We would need to add a new section (or something in the `sds4install` section) to define the name of the external library, its GitHub repository URL, and the tag to checkout (or master). Maybe something like

```
[sdss4install]
evilmake = True
no_python_package = True
external_dependencies = 
	coyote = https://github.com/idl-coyote/coyote, master
	goddard = https://github.com/wlandsman/IDLAstro, 1.0.1
```

**Comment by joelbrownstein** [comment]
This looks like a good plan, and I'll iterate with @nbmurphy on its implemenation

**Comment by nbmurphy** [comment]
I decided to make an `[external_dependencies]` section in the `ini` file. 
I would like to propose the following JSON standard for the `keys` in this section:
```
{
 "install_product": {
   "url": "product_url",
   "version": "product_version"
  },
 "paths": {
  "idl": ["idl_dir0","idl_dirN"],
  "shell": ["shell_dir0","shell_dirN"],
  "python": ["python_dir0","python_dirN"]
 }
}
```
`product_url` is of the form `https://github.com/product_owner/product_name`, `git@github.com:product_owner/product_name`, or `https://svn.sdss.org/product_owner/product_name`, and  `idl_dirN`, `bin_dirN`, and `python_dirN` are subdirectories with respect to the product's git repository root directory.
