### ISSUE TITLE
sdss_access tree modulefiles are missing the PYTHONPATH

### ISSUE THREAD

**Issue by joelbrownstein** [sdss/sdss_install#6]
When running`sdss_install tree master -G -F` the generated modulefiles seem to be missing the line which allows tree to be imported in python:

`prepend-path PYTHONPATH $PRODUCT_DIR/python`

**Comment by nbmurphy** [comment]
@joelbrownstein and I found that the line `prepend-path PYTHONPATH $PRODUCT_DIR/python` was actually missing in `bin/install_tree.py` of the tree product itself. We made the changes in GitHub and successfully tested the change both on cypher and at Utah.
