### ISSUE TITLE
fix yaml loader to handle new pyyaml 5.1 spec

### ISSUE THREAD

**Issue by havok2063** [sdss/sdss_install#8]
The yaml loader needs to be updated to handle the new 5.1 spec which requires a `Loader` to be specified.  It issues a warning but continues to work in the meantime.  This can be made flexible enough to handle old and new yaml specs.  For 5.1+ it needs to be `yaml.load(file, Loader=yaml.FullLoader)`

`/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/__init__.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.    config = yaml.load(open(os.path.dirname(__file__) + '/etc/{0}.yml'.format(NAME)))
`

**Comment by nbmurphy** [comment]
Updated the yaml.load method, adding the input `Loader=yaml.SafeLoader`. Instead adding the input `Loader=yaml.FullLoader`, as suggested [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation), throws the error `AttributeError: 'module' object has no attribute 'FullLoader'`. @havok2063 with this update, are you still getting the reported warning? (I never got a warning on my machine.)

**Comment by nbmurphy** [comment]
@havok2063 showed me a way to update the yaml loader while making it backwards compatible. The solution was successfully tested by @havok2063.
